# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '4weekM' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 4weekM
  pod 'Alamofire'
  target '4weekMTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '4weekMUITests' do
    # Pods for testing
  end

end
