# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'socialLogin' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for socialLogin

  pod 'KakaoSDK'

  target 'socialLoginTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'socialLoginUITests' do
    # Pods for testing
  end

end
